#!/usr/bin/env bash

# Portuguese Language Strings for NixOS Configuration Installer
# Arquivo de strings em português para o Instalador de Configuração NixOS

# Main installer messages
MSG_TITLE="🚀 Instalador da Configuração NixOS"
MSG_WELCOME="Bem-vindo ao instalador da configuração modular do NixOS!"
MSG_WARNING="⚠️ ATENÇÃO: Este script irá:"
MSG_WARNING1="- Fazer backup da sua configuração atual"
MSG_WARNING2="- Substituir /etc/nixos com esta configuração"
MSG_WARNING3="- Gerar um novo variables.nix personalizado"
MSG_CONTINUE="Deseja continuar? (s/N)"
MSG_BACKUP="📦 Fazendo backup da configuração atual..."
MSG_CLONE="📥 Clonando a nova configuração..."
MSG_CONFIG="🔧 Configurando o sistema..."

# Configuration prompts
MSG_USERNAME="Nome de usuário"
MSG_HOSTNAME="Nome do host"
MSG_GPU="Tipo de GPU"
MSG_LAPTOP="Este é um laptop?"
MSG_BLUETOOTH="Ativar Bluetooth?"
MSG_GAMING="Instalar pacotes de gaming?"
MSG_DEVELOPMENT="Instalar ferramentas de desenvolvimento?"
MSG_MEDIA="Instalar aplicações de mídia?"
MSG_VIRTUALBOX="Ativar VirtualBox?"
MSG_POLKIT="Ativar autenticação gráfica (Polkit GNOME)?"
MSG_FAUXMO="Ativar integração com Alexa (Fauxmo)?"
MSG_KANSHI="Ativar gerenciamento automático de displays (Kanshi)?"
MSG_WAKE_ON_LAN="Ativar Wake on LAN?"
MSG_AUTO_UPDATE="Ativar atualizações automáticas semanais?"
MSG_THEME_SELECTION="🎨 Seleção de Tema GTK"
MSG_THEME="Escolha seu tema GTK:"
MSG_ICON_SELECTION="🖼️ Seleção de Tema de Ícones"
MSG_ICON="Escolha seu tema de ícones:"
MSG_DISK="UUID do disco adicional (opcional, Enter para pular)"
MSG_MOUNT="Ponto de montagem para o disco"

# Installation process
MSG_GENERATING="📝 Gerando variables.nix personalizado..."
MSG_REVIEW="📋 Revisão das suas configurações:"
MSG_CONFIRM="As configurações estão corretas?"
MSG_CHANGE="Deseja alterar alguma configuração?"
MSG_BACKUP_ASK="Deseja fazer backup da configuração atual?"
MSG_REBUILD_ASK="Deseja que o script execute o rebuild automaticamente?"
MSG_REBUILDING="🔄 Executando rebuild do sistema..."
MSG_COMPLETE="✅ Instalação completa!"
MSG_REBUILD="Para aplicar as configurações, execute: rebuild"
MSG_ROOT_ERROR="Não execute este script como root!"

# Disk detection and configuration
MSG_NO_VALID_PARTITIONS="Nenhuma partição adicional com filesystem válido encontrada."
MSG_NO_ADDITIONAL_DISKS="Nenhum disco adicional detectado."
MSG_CHOICE_PROMPT="Escolha (1-3):"
MSG_INVALID_CHOICE="Escolha inválida. Selecione 1-3"

# Preset system
MSG_PRESET_FOUND="📁 Configuração salva encontrada!"
MSG_USE_PRESET="Deseja usar esta configuração salva?"
MSG_USING_SAVED="✅ Usando configuração salva!"
MSG_IGNORED_MSG="Configuração salva ignorada. Coletando nova configuração..."
MSG_SAVE_PRESET="Deseja salvar esta configuração para reuso futuro?"
MSG_CONFIG_COMPLETE="Configuração completa! Agora vamos instalar os arquivos..."

# Backup and installation
MSG_BACKUP_CURRENT="Criando backup da configuração atual..."
MSG_BACKUP_CREATED="Backup criado em:"
MSG_NO_BACKUP_FOUND="Nenhuma configuração anterior encontrada para backup."
MSG_INSTALLING_CONFIG="Instalando nova configuração NixOS..."
MSG_COPYING_FILES="Copiando arquivos de configuração..."
MSG_FILES_COPIED="✅ Arquivos de configuração copiados (excluindo documentação)"
MSG_GENERATING_HW="Gerando configuração de hardware para este sistema..."
MSG_HW_GENERATED="✅ Configuração de hardware gerada"
MSG_CONFIG_INSTALLED="Configuração instalada com sucesso!"

# Rebuild status
MSG_REBUILD_SUCCESS="Rebuild concluído com sucesso!"
MSG_REBUILD_FAILED="Rebuild falhou! Você pode executá-lo manualmente depois com: rebuild"
MSG_NEXT_STEPS="Próximos passos:"
MSG_STEP1="1. Revise /etc/nixos/config/variables.nix se necessário"
MSG_STEP2="2. Execute: rebuild"
MSG_STEP3="3. Reinicie o sistema"
MSG_STEP4="4. Configure suas aplicações favoritas"

# System cleanup
MSG_CLEANER_OFFER="Deseja executar nixos-cleaner para limpar o sistema?"
MSG_CLEANER_RUNNING="🧹 Executando nixos-cleaner..."
MSG_CLEANER_SUCCESS="✅ Sistema limpo com sucesso!"
MSG_CLEANER_ERROR="❌ Erro ao executar nixos-cleaner"

# Dependencies and system validation
MSG_DEPENDENCY_CHECK="Verificando dependências do sistema..."
MSG_NIXOS_CHECK="Verificando se está rodando no NixOS..."
MSG_NOT_NIXOS="❌ Este script deve ser executado no NixOS!"
MSG_MISSING_DEPS="❌ Dependências ausentes:"
MSG_INSTALL_DEPS="Por favor, instale as dependências ausentes e tente novamente."
MSG_DEPS_OK="✅ Todas as dependências encontradas"
MSG_INSTALLER_FOR_NIXOS="Este instalador foi projetado especificamente para NixOS."
MSG_NIXOS_FILE_NOT_FOUND="Arquivo /etc/NIXOS não encontrado."
MSG_NIXOS_INSTALL_CMD="No NixOS, você pode instalar com:"
MSG_NIXOS_REBUILD_NOT_FOUND="⚠️ nixos-rebuild não encontrado no PATH"
MSG_NIXOS_NORMAL_ISO="Isso é normal se você ainda não instalou o NixOS completamente."
MSG_MANUAL_REBUILD_NEEDED="O rebuild manual será necessário após a instalação."

# Validation and error messages
MSG_INVALID_GPU_TYPE="❌ Tipo de GPU inválido:"
MSG_VALID_GPU_VALUES="Valores válidos: amd, nvidia, intel"
MSG_INVALID_BOOLEAN="❌ Valor inválido para"
MSG_BOOLEAN_VALUES="Deve ser 'true' ou 'false'"
MSG_INVALID_USERNAME="❌ Nome de usuário inválido:"
MSG_USERNAME_RULES="Deve começar com letra e conter apenas letras, números, _ ou -"
MSG_INVALID_HOSTNAME="❌ Nome do host inválido:"
MSG_HOSTNAME_RULES="Deve começar com letra e conter apenas letras, números ou -"
MSG_CONFIG_FIXED="✅ Configuração corrigida!"
MSG_SAVE_CORRECTIONS_QUESTION="Deseja salvar as correções no preset?"
MSG_SAVE_CORRECTIONS="Salvar correções?"

# Root execution check
MSG_NO_ROOT_EXECUTION="❌ ERRO: Não execute este instalador como root!"
MSG_ROOT_SOLUTION="💡 Execute como usuário normal: ./install.sh"
MSG_ROOT_SECURITY_RISK="⚠️ Executar como root é perigoso e desnecessário"

# Security checks
MSG_SECURITY_CHECK="🔐 Verificando ambiente de segurança..."
MSG_CONTAINER_DETECTED="⚠️ Executando em container. Funcionalidade limitada"
MSG_UEFI_DETECTED="✅ UEFI boot detectado"
MSG_LEGACY_BIOS="⚠️ Legacy BIOS. Alguns recursos podem não funcionar"
MSG_SECURE_BOOT_WARNING="⚠️ Secure Boot ativo. Drivers NVIDIA podem ter problemas"

# Connectivity checks
MSG_CONNECTIVITY_CHECK="🌐 Verificando conectividade..."
MSG_NO_INTERNET="❌ ERRO: Sem conexão com internet"
MSG_CHECK_NETWORK="💡 Verifique sua conexão de rede antes de continuar"
MSG_NIXOS_CACHE_SLOW="⚠️ Cache NixOS inacessível. Downloads podem ser muito lentos"
MSG_CHECK_FIREWALL="💡 Considere verificar firewall/proxy"
MSG_NIXOS_CACHE_OK="✅ Cache NixOS acessível"
MSG_GITHUB_UNAVAILABLE="⚠️ GitHub inacessível. Dotfiles podem falhar"
MSG_GITHUB_OK="✅ GitHub acessível"

# Input validation
MSG_VALIDATING_INPUT="🔍 Validando entrada do usuário..."
MSG_USERNAME_START_LETTER="💡 Deve começar com letra"
MSG_USERNAME_LENGTH="❌ ERRO: Username deve ter 2-32 caracteres"
MSG_USERNAME_RESERVED="❌ ERRO: Username '%s' é reservado pelo sistema"
MSG_HOSTNAME_LENGTH_RULE="💡 Máximo 63 caracteres, não pode começar/terminar com hífen"
MSG_HOSTNAME_LENGTH="❌ ERRO: Hostname deve ter 1-63 caracteres"
MSG_USERNAME_OK="✅ Username"
MSG_HOSTNAME_OK="✅ Hostname"

# Disk detection and configuration
MSG_DETECTING_DISKS="Detectando discos adicionais..."
MSG_ADDITIONAL_DISKS_DETECTED="Discos/partições adicionais detectados:"
MSG_DISK_SIZE="Tamanho:"
MSG_DISK_FILESYSTEM="Sistema de arquivos:"
MSG_DISK_LABEL="Label:"
MSG_NO_LABEL="sem label"
MSG_CONFIGURE_ADDITIONAL_DISKS="Deseja configurar discos adicionais para montagem automática?"
MSG_CONFIGURING_DISKS="Configurando discos adicionais..."
MSG_DISK_INFO="Disco"
MSG_CONFIGURE_DISK="Configurar este disco para montagem automática?"
MSG_MOUNT_POINT="Ponto de montagem"
MSG_MOUNT_OPTIONS_DISK="Opções de montagem para este disco:"
MSG_RECOMMENDED_OPTIONS="Opções padrão recomendadas:"
MSG_DEFAULTS_OPTION="- defaults: opções básicas de montagem"
MSG_GVFS_OPTION="- x-gvfs-show: mostra disco no gerenciador de arquivos"
MSG_USE_DEFAULT_OPTIONS="Usar as opções padrão recomendadas?"
MSG_COMMON_MOUNT_OPTIONS="Opções comuns de montagem:"
MSG_ENTER_MOUNT_OPTIONS="Digite as opções de montagem (separadas por vírgula)"
MSG_DISK_CONFIGURED="Disco configurado:"
MSG_WITH_OPTIONS="com opções"

# Common responses
MSG_YES="s"
MSG_NO="n"

# Preset display
MSG_SAVED_CONFIG_FOUND="Configuração salva encontrada:"
MSG_CONFIGURED_TEXT="configurado(s)"
MSG_DISK_DETAILS="Detalhes dos discos:"
MSG_MOUNT_TEXT="Montagem:"
MSG_FILESYSTEM_TEXT="Sistema:"
MSG_OPTIONS_TEXT="Opções:"
MSG_NONE_TEXT="Nenhum"
MSG_CONFIG_CREATED_ON="Configuração criada em:"

# Mount options descriptions
MSG_DEFAULTS_DESC="opções padrão básicas"
MSG_GVFS_DESC="mostrar no gerenciador arquivos"
MSG_NOATIME_DESC="não atualizar tempo de acesso (performance)"
MSG_USER_DESC="permitir usuários montar"
MSG_COMPRESS_DESC="compressão (apenas btrfs)"
MSG_SUBVOL_DESC="subvolume específico (btrfs)"
MSG_CONFIG_SAVED_TO="Configuração salva em:"

# System validation
MSG_SYSTEM_VALIDATION="Validando sistema..."
MSG_GPU_DETECTION="Detectando hardware de GPU..."
MSG_GPU_DETECTED="GPU detectada automaticamente:"
MSG_GPU_CONFIRM="Confirmar GPU detectada?"
MSG_GPU_MANUAL="Seleção manual de GPU necessária"
MSG_GPU_AMD_DETECTED="AMD GPU detectada"
MSG_GPU_NVIDIA_DETECTED="NVIDIA GPU detectada"
MSG_GPU_INTEL_DETECTED="Intel GPU detectada"
MSG_GPU_DRIVER_RECOMMENDATION="Driver recomendado:"
MSG_GPU_AMDGPU_OPENSOURCE="AMDGPU (código aberto)"
MSG_GPU_NVIDIA_PROPRIETARY="Proprietário NVIDIA"
MSG_GPU_INTEL_OPENSOURCE="Intel (código aberto)"
MSG_GPU_CONFIG_TYPE="Configuração: gpu.type ="

# Requirements check
MSG_REQUIREMENTS_CHECK="Verificando requisitos do sistema"
MSG_RAM_DETECTED="RAM detectada:"
MSG_DISK_SPACE_DETECTED="Espaço disponível:"
MSG_ARCHITECTURE_DETECTED="Arquitetura:"
MSG_REQUIREMENTS_MET="Sistema atende aos requisitos"
MSG_REQUIREMENTS_FAILED="Sistema não atende aos requisitos mínimos"
MSG_INSUFFICIENT_RAM="RAM insuficiente"
MSG_INSUFFICIENT_DISK="Espaço em disco insuficiente"
MSG_UNSUPPORTED_ARCH="Arquitetura não suportada"

# Dotfiles configuration
MSG_DOTFILES_CHECK="Verificando dotfiles..."
MSG_DOTFILES_CONFIGURE="Configurar dotfiles para aplicação automática?"
MSG_DOTFILES_FOUND="Pasta dotfiles encontrada"
MSG_DOTFILES_NOT_FOUND="Pasta dotfiles não encontrada"
MSG_DOTFILES_EMPTY="Pasta dotfiles vazia"
MSG_DOTFILES_DOWNLOAD="Deseja baixar os dotfiles do GitHub?"
MSG_DOTFILES_DOWNLOADING="Baixando dotfiles..."
MSG_DOTFILES_APPLYING="Aplicando dotfiles com stow..."
MSG_DOTFILES_SUCCESS="Dotfiles aplicados com sucesso!"
MSG_DOTFILES_ERROR="Erro ao aplicar dotfiles"
MSG_DOTFILES_SKIP="Pulando configuração de dotfiles"
MSG_STOW_NOT_FOUND="GNU Stow não encontrado"
MSG_STOW_INSTALLING="Instalando GNU Stow..."
MSG_DOTFILES_DIRECT_STRUCTURE="Usando estrutura direta de dotfiles (stow .)"
MSG_DOTFILES_PACKAGES_FOUND="pacotes encontrados:"
MSG_DOTFILES_LOCATION="Onde deseja armazenar os dotfiles?"
MSG_DOTFILES_LOCATION_SCRIPT="Na pasta do script (~/dotfiles)"
MSG_DOTFILES_LOCATION_HIDDEN="Pasta oculta (~/.dotfiles) - Recomendada"
MSG_DOTFILES_LOCATION_CUSTOM="Localização personalizada"
MSG_DOTFILES_CUSTOM_PATH="Digite o caminho desejado:"
MSG_DOTFILES_EXISTS_ELSEWHERE="Dotfiles encontrados em localização diferente"
MSG_DOTFILES_MOVE_OR_COPY="Deseja mover ou copiar para nova localização?"
MSG_DOTFILES_MOVE="Mover arquivos"
MSG_DOTFILES_COPY="Copiar arquivos"
MSG_DOTFILES_KEEP_CURRENT="Manter localização atual"
MSG_DOTFILES_MOVING="Movendo dotfiles..."
MSG_DOTFILES_COPYING="Copiando dotfiles..."
MSG_DOTFILES_RELOCATED="Dotfiles realocados com sucesso"
MSG_DOTFILES_PREPARED="Dotfiles preparados para aplicação pós-rebuild"
MSG_DOTFILES_WILL_APPLY="Dotfiles serão aplicados após rebuild bem-sucedido"
MSG_DOTFILES_SELECTED_LOCATION="Localização selecionada:"
MSG_DOTFILES_ENABLED="Dotfiles ativados:"
MSG_DOTFILES_LOCATION_DISPLAY="Localização dos dotfiles:"

# Rollback generations configuration
MSG_ROLLBACK_GENERATIONS="Quantas gerações de rollback manter no sistema?"
MSG_ROLLBACK_GENERATIONS_DESC="Gerações permitem reverter atualizações do sistema"
MSG_ROLLBACK_DEFAULT_DESC="Padrão: 2 gerações (recomendado para uso diário)"
MSG_ROLLBACK_EXAMPLES="Exemplos: 1 (mínimo), 2 (padrão), 5 (desenvolvimento)"