#!/usr/bin/env bash

# English Language Strings for NixOS Configuration Installer
# English string definitions for the NixOS Configuration Installer

# Main installer messages
MSG_TITLE="🚀 NixOS Configuration Installer"
MSG_WELCOME="Welcome to the modular NixOS configuration installer!"
MSG_WARNING="⚠️ WARNING: This script will:"
MSG_WARNING1="- Backup your current configuration"
MSG_WARNING2="- Replace /etc/nixos with this configuration"
MSG_WARNING3="- Generate a new custom variables.nix"
MSG_CONTINUE="Do you want to continue? (y/N)"
MSG_BACKUP="📦 Backing up current configuration..."
MSG_CLONE="📥 Cloning new configuration..."
MSG_CONFIG="🔧 Configuring the system..."

# Configuration prompts
MSG_USERNAME="Username"
MSG_HOSTNAME="Hostname"
MSG_GPU="GPU type"
MSG_LAPTOP="Is this a laptop?"
MSG_BLUETOOTH="Enable Bluetooth?"
MSG_GAMING="Install gaming packages?"
MSG_DEVELOPMENT="Install development tools?"
MSG_MEDIA="Install media applications?"
MSG_VIRTUALBOX="Enable VirtualBox?"
MSG_POLKIT="Enable GUI authentication (Polkit GNOME)?"
MSG_FAUXMO="Enable Alexa integration (Fauxmo)?"
MSG_AUTO_UPDATE="Enable automatic system updates (weekly)?"
MSG_THEME_SELECTION="🎨 GTK Theme Selection"
MSG_THEME="Choose your GTK theme:"
MSG_ICON_SELECTION="🖼️ Icon Theme Selection"
MSG_ICON="Choose your icon theme:"
MSG_DISK="Additional disk UUID (optional, Enter to skip)"
MSG_MOUNT="Mount point for the disk"

# Installation process
MSG_GENERATING="📝 Generating custom variables.nix..."
MSG_REVIEW="📋 Review of your configuration:"
MSG_CONFIRM="Are the configurations correct?"
MSG_CHANGE="Do you want to change any configuration?"
MSG_BACKUP_ASK="Do you want to backup the current configuration?"
MSG_REBUILD_ASK="Do you want the script to automatically run rebuild?"
MSG_REBUILDING="🔄 Running system rebuild..."
MSG_COMPLETE="✅ Installation complete!"
MSG_REBUILD="To apply the configuration, run: rebuild"
MSG_ROOT_ERROR="Don't run this script as root!"

# Disk detection and configuration
MSG_NO_VALID_PARTITIONS="No additional partitions with valid filesystem found."
MSG_NO_ADDITIONAL_DISKS="No additional disks detected."
MSG_CHOICE_PROMPT="Choice (1-3):"
MSG_INVALID_CHOICE="Invalid choice. Please select 1-3"

# Preset system
MSG_PRESET_FOUND="📁 Saved configuration found!"
MSG_USE_PRESET="Do you want to use this saved configuration?"
MSG_USING_SAVED="✅ Using saved configuration!"
MSG_IGNORED_MSG="Saved configuration ignored. Collecting new configuration..."
MSG_SAVE_PRESET="Do you want to save this configuration for future reuse?"
MSG_CONFIG_COMPLETE="Configuration complete! Now let's install the files..."

# Backup and installation
MSG_BACKUP_CURRENT="Creating backup of current configuration..."
MSG_BACKUP_CREATED="Backup created at:"
MSG_NO_BACKUP_FOUND="No previous configuration found to backup."
MSG_INSTALLING_CONFIG="Installing new NixOS configuration..."
MSG_COPYING_FILES="Copying configuration files..."
MSG_FILES_COPIED="✅ Configuration files copied (excluding documentation)"
MSG_GENERATING_HW="Generating hardware configuration for this system..."
MSG_HW_GENERATED="✅ Hardware configuration generated"
MSG_CONFIG_INSTALLED="Configuration installed successfully!"

# Rebuild status
MSG_REBUILD_SUCCESS="Rebuild completed successfully!"
MSG_REBUILD_FAILED="Rebuild failed! You can run it manually later with: rebuild"
MSG_NEXT_STEPS="Next steps:"
MSG_STEP1="1. Review /etc/nixos/config/variables.nix if needed"
MSG_STEP2="2. Run: rebuild"
MSG_STEP3="3. Reboot the system"
MSG_STEP4="4. Configure your favorite applications"

# System cleanup
MSG_CLEANER_OFFER="Do you want to run nixos-cleaner to clean up the system?"
MSG_CLEANER_RUNNING="🧹 Running nixos-cleaner..."
MSG_CLEANER_SUCCESS="✅ System cleaned successfully!"
MSG_CLEANER_ERROR="❌ Error running nixos-cleaner"

# Dependencies and system validation
MSG_DEPENDENCY_CHECK="Checking system dependencies..."
MSG_NIXOS_CHECK="Checking if running on NixOS..."
MSG_NOT_NIXOS="❌ This script must be run on NixOS!"
MSG_MISSING_DEPS="❌ Missing dependencies:"
MSG_INSTALL_DEPS="Please install the missing dependencies and try again."
MSG_DEPS_OK="✅ All dependencies found"
MSG_INSTALLER_FOR_NIXOS="This installer is designed specifically for NixOS."
MSG_NIXOS_FILE_NOT_FOUND="Could not find /etc/NIXOS file."
MSG_NIXOS_INSTALL_CMD="On NixOS, you can install with:"
MSG_NIXOS_REBUILD_NOT_FOUND="⚠️ nixos-rebuild not found in PATH"
MSG_NIXOS_NORMAL_ISO="This is normal if you haven't fully installed NixOS yet."
MSG_MANUAL_REBUILD_NEEDED="Manual rebuild will be required after installation."

# Validation and error messages
MSG_INVALID_GPU_TYPE="❌ Invalid GPU type:"
MSG_VALID_GPU_VALUES="Valid values: amd, nvidia, intel"
MSG_INVALID_BOOLEAN="❌ Invalid value for"
MSG_BOOLEAN_VALUES="Must be 'true' or 'false'"
MSG_INVALID_USERNAME="❌ Invalid username:"
MSG_USERNAME_RULES="Must start with letter and contain only letters, numbers, _ or -"
MSG_INVALID_HOSTNAME="❌ Invalid hostname:"
MSG_HOSTNAME_RULES="Must start with letter and contain only letters, numbers or -"
MSG_CONFIG_FIXED="✅ Configuration fixed!"
MSG_SAVE_CORRECTIONS_QUESTION="Do you want to save the corrections to the preset?"
MSG_SAVE_CORRECTIONS="Save corrections?"

# Disk detection and configuration
MSG_DETECTING_DISKS="Detecting additional disks..."
MSG_ADDITIONAL_DISKS_DETECTED="Additional disks/partitions detected:"
MSG_DISK_SIZE="Size:"
MSG_DISK_FILESYSTEM="Filesystem:"
MSG_DISK_LABEL="Label:"
MSG_NO_LABEL="no label"
MSG_CONFIGURE_ADDITIONAL_DISKS="Do you want to configure additional disks for automatic mounting?"
MSG_CONFIGURING_DISKS="Configuring additional disks..."
MSG_DISK_INFO="Disk"
MSG_CONFIGURE_DISK="Configure this disk for automatic mounting?"
MSG_MOUNT_POINT="Mount point"
MSG_MOUNT_OPTIONS_DISK="Mount options for this disk:"
MSG_RECOMMENDED_OPTIONS="Recommended default options:"
MSG_DEFAULTS_OPTION="- defaults: basic mount options"
MSG_GVFS_OPTION="- x-gvfs-show: show disk in file manager"
MSG_USE_DEFAULT_OPTIONS="Use the recommended default options?"
MSG_COMMON_MOUNT_OPTIONS="Common mount options:"
MSG_ENTER_MOUNT_OPTIONS="Enter mount options (comma separated)"
MSG_DISK_CONFIGURED="Disk configured:"
MSG_WITH_OPTIONS="with options"

# Common responses
MSG_YES="y"
MSG_NO="n"

# Preset display
MSG_SAVED_CONFIG_FOUND="Saved configuration found:"
MSG_CONFIGURED_TEXT="configured"
MSG_DISK_DETAILS="Disk details:"
MSG_MOUNT_TEXT="Mount:"
MSG_FILESYSTEM_TEXT="Filesystem:"
MSG_OPTIONS_TEXT="Options:"
MSG_NONE_TEXT="None"
MSG_CONFIG_CREATED_ON="Configuration created on:"

# Mount options descriptions
MSG_DEFAULTS_DESC="basic default options"
MSG_GVFS_DESC="show in file manager"
MSG_NOATIME_DESC="don't update access time (performance)"
MSG_USER_DESC="allow users to mount"
MSG_COMPRESS_DESC="compression (btrfs only)"
MSG_SUBVOL_DESC="specific subvolume (btrfs)"
MSG_CONFIG_SAVED_TO="Configuration saved to:"

# System validation
MSG_SYSTEM_VALIDATION="Validating system..."
MSG_GPU_DETECTION="Detecting GPU hardware..."
MSG_GPU_DETECTED="GPU detected automatically:"
MSG_GPU_CONFIRM="Confirm detected GPU?"
MSG_GPU_MANUAL="Manual GPU selection required"
MSG_GPU_AMD_DETECTED="AMD GPU detected"
MSG_GPU_NVIDIA_DETECTED="NVIDIA GPU detected"
MSG_GPU_INTEL_DETECTED="Intel GPU detected"
MSG_GPU_DRIVER_RECOMMENDATION="Recommended driver:"
MSG_GPU_AMDGPU_OPENSOURCE="AMDGPU (open-source)"
MSG_GPU_NVIDIA_PROPRIETARY="Proprietary NVIDIA"
MSG_GPU_INTEL_OPENSOURCE="Intel (open-source)"
MSG_GPU_CONFIG_TYPE="Configuration: gpu.type ="

# Requirements check
MSG_REQUIREMENTS_CHECK="Checking system requirements"
MSG_RAM_DETECTED="RAM detected:"
MSG_DISK_SPACE_DETECTED="Available space:"
MSG_ARCHITECTURE_DETECTED="Architecture:"
MSG_REQUIREMENTS_MET="System meets requirements"
MSG_REQUIREMENTS_FAILED="System does not meet minimum requirements"
MSG_INSUFFICIENT_RAM="Insufficient RAM"
MSG_INSUFFICIENT_DISK="Insufficient disk space"
MSG_UNSUPPORTED_ARCH="Unsupported architecture"

# Dotfiles configuration
MSG_DOTFILES_CHECK="Checking dotfiles..."
MSG_DOTFILES_CONFIGURE="Configure dotfiles for automatic application?"
MSG_DOTFILES_FOUND="Dotfiles folder found"
MSG_DOTFILES_NOT_FOUND="Dotfiles folder not found"
MSG_DOTFILES_EMPTY="Dotfiles folder is empty"
MSG_DOTFILES_DOWNLOAD="Download dotfiles from GitHub?"
MSG_DOTFILES_DOWNLOADING="Downloading dotfiles..."
MSG_DOTFILES_APPLYING="Applying dotfiles with stow..."
MSG_DOTFILES_SUCCESS="Dotfiles applied successfully!"
MSG_DOTFILES_ERROR="Error applying dotfiles"
MSG_DOTFILES_SKIP="Skipping dotfiles configuration"
MSG_STOW_NOT_FOUND="GNU Stow not found"
MSG_STOW_INSTALLING="Installing GNU Stow..."
MSG_DOTFILES_DIRECT_STRUCTURE="Using direct dotfiles structure (stow .)"
MSG_DOTFILES_PACKAGES_FOUND="packages found:"
MSG_DOTFILES_LOCATION="Where do you want to store dotfiles?"
MSG_DOTFILES_LOCATION_SCRIPT="In script folder (~/dotfiles)"
MSG_DOTFILES_LOCATION_HIDDEN="Hidden folder (~/.dotfiles) - Recommended"
MSG_DOTFILES_LOCATION_CUSTOM="Custom location"
MSG_DOTFILES_CUSTOM_PATH="Enter desired path:"
MSG_DOTFILES_EXISTS_ELSEWHERE="Dotfiles found in different location"
MSG_DOTFILES_MOVE_OR_COPY="Move or copy to new location?"
MSG_DOTFILES_MOVE="Move files"
MSG_DOTFILES_COPY="Copy files"
MSG_DOTFILES_KEEP_CURRENT="Keep current location"
MSG_DOTFILES_MOVING="Moving dotfiles..."
MSG_DOTFILES_COPYING="Copying dotfiles..."
MSG_DOTFILES_RELOCATED="Dotfiles relocated successfully"
MSG_DOTFILES_PREPARED="Dotfiles prepared for post-rebuild application"
MSG_DOTFILES_WILL_APPLY="Dotfiles will be applied after successful rebuild"
MSG_DOTFILES_SELECTED_LOCATION="Selected location:"
MSG_DOTFILES_ENABLED="Dotfiles enabled:"
MSG_DOTFILES_LOCATION_DISPLAY="Dotfiles location:"